### ISSUE TITLE
12.0 : Unable to load picture document

### ISSUE THREAD

**Issue by gregory-moka** [OCA/dms#32] opened 2020-10-20 11:19 UTC
When I try tu upload a picture on a document (to replace the document type icon), I recieve this error :  
```python
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 27

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/fields.py", line 1028, in __get__
    value = record.env.cache.get(record, self)
  File "/.repo_requirements/odoo/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('dms.file(27,).thumbnail', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-12.0/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/dms/dms/models/dms_file.py", line 437, in read
    return super(File, self).read(fields, load=load)
  File "/.repo_requirements/odoo/odoo/models.py", line 2820, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/.repo_requirements/odoo/odoo/models.py", line 5148, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/.repo_requirements/odoo/odoo/fields.py", line 1032, in __get__
    self.determine_value(record)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1145, in determine_value
    self.compute_value(recs)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1099, in compute_value
    self._compute_value(records)
  File "/.repo_requirements/odoo/odoo/fields.py", line 1090, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/build/OCA/dms/dms/models/mixins_thumbnail.py", line 83, in _compute_thumbnail
    record.thumbnail, return_big=True, avoid_resize_medium=True
  File "/.repo_requirements/odoo/odoo/tools/image.py", line 292, in image_get_resized_images
    return_dict[big_name] = image_resize_image_big(base64_source, avoid_if_small=avoid_resize_big, size=size_big)
  File "/.repo_requirements/odoo/odoo/tools/image.py", line 168, in image_resize_image_big
    return image_resize_image(base64_source, size, encoding, filetype, avoid_if_small)
  File "/.repo_requirements/odoo/odoo/tools/image.py", line 69, in image_resize_image
    image = Image.open(image_stream)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/PIL/Image.py", line 2349, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f64bd4172b0>
```

**Comment by pedrobaeza** [comment] 2020-10-20 11:21
This is clearly a problem with the image itself, as it's not recognized by PIL.

**Comment by gregory-moka** [comment] 2020-10-20 11:47
I only try to upload this file (named nature.jpg), by I tried with other format (jpg, jpeg, png). It's always the same result.
![nature](https://user-images.githubusercontent.com/45974412/96581872-c60f6400-12da-11eb-8aaf-2a3f59273ba5.jpg)

**Comment by pedrobaeza** [comment] 2020-10-20 12:12
It seems an incorrect installation of PIL library. Are you trying on OCA's runbot?

**Comment by gregory-moka** [comment] 2020-10-21 05:33
Yes, I tried on runbot after testing on a personnal database.

**Comment by pedrobaeza** [comment] 2020-10-21 06:48
OK, I see the problem. @etobella can you please check? I think the problem is to make the icon of the file type editable on the document.

**Comment by etobella** [comment] 2020-10-21 08:17
I will check, thanks

**Comment by etobella** [comment] 2020-10-21 08:50
As the PR already exists that fixes the issue, I will close the Issue. Thanks @gregory-moka

**Closed as completed by etobella** 2020-10-21 08:50 UTC
