### ISSUE TITLE
User with group on the folder can't create a file in this folder

### ISSUE THREAD

**Issue by stmar** [OCA/dms#382] opened 2024-12-10 10:20 UTC
## Module
dms

## Describe the bug
User with group with create permission on the folder can't create a file in this folder

## To Reproduce
**Affected versions**:
tested in version 16

1. Add a group A with creation permission in Configuration> System > Acess group
2. Go to a directory, add the group A in groups tab with create permission
3. when connected with user with group A, create a file, select the directory. When saving the form there is an ir.rule error

**Expected behavior**

No error

**Additional context**
In the ir.rule, the domain is [('permission_create', '=', user.id) whereas permission_create is a boolean field

**Comment by victoralmau** [comment] 2024-12-10 12:39
Can you explain a little more the steps you do to reproduce the error (maybe a mini-video) and/or if another module is causing the error.

The use case you indicate works correctly.
![ejemplo-2](https://github.com/user-attachments/assets/c11e9229-5198-4903-90f8-9eb03e41ae28)

**Comment by stmar** [comment] 2024-12-12 08:57
Here is the video. The instance used to test : http://oca-dms-16-0-a56dd40ab485.runboat.odoo-community.org/web
<video src='https://github.com/user-attachments/assets/7e55bb29-feda-450e-bea4-3ebdbf80cf36' width=180/>

**Comment by stmar** [comment] 2024-12-12 12:48
> Can you explain a little more the steps you do to reproduce the error (maybe a mini-video) and/or if another module is causing the error.
> 
> The use case you indicate works correctly. 

Yes, it works when you create from file menu but not from directory menu

**Comment by victoralmau** [comment] 2024-12-20 16:06
Ok, I understand the use case. Honestly I don't think it's a bug, I mean, if the user only has create permission and not write permission, it's “_normal_” that when trying to modify the directory and save it shows the error (even if he can create the file directly from the file menu), don't you think? What do you think @pedrobaeza ?

**Comment by pedrobaeza** [comment] 2024-12-20 16:16
Yes, it's not a bug, and it's congruent with for example Odoo ACLs: if you leave create and not write, you can create it but not modify it. Closing as no bug.

**Closed as completed by pedrobaeza** 2024-12-20 16:16 UTC
Labels: bug
